# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(450, 380))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"     QWidget#centralwidget {\n"
"         background-color: #ebebeb;\n"
"     }\n"
"     QLabel {\n"
"         font-family: \"Segoe UI\", Arial, sans-serif;\n"
"         color: #000000;\n"
"         font-size: 12px;\n"
"     }\n"
"     QLabel#label_title {\n"
"         font-size: 20px;\n"
"         font-weight: bold;\n"
"         color: #000000;\n"
"         margin-bottom: 2px;\n"
"     }\n"
"     QLabel#label_subtitle {\n"
"         font-size: 11px;\n"
"         color: #555555;\n"
"         margin-bottom: 8px;\n"
"         font-style: italic;\n"
"     }\n"
"     QTextEdit, QLineEdit {\n"
"         background-color: #ffffff;\n"
"         border: 1px solid #adadad;\n"
"         color: #000000;\n"
"         font-family: \"Segoe UI\", Arial, sans-serif;\n"
"         font-size: 12px;\n"
"         padding: 3px;\n"
"     }\n"
"     QPushButton {\n"
"         background-color: #ffffff;\n"
"         border: 1px solid #adadad;\n"
"         border-radius: 5px;\n"
"         padding: 4px 20px;\n"
"         font-family: \"Segoe UI\", Arial, sans-serif;\n"
"         font-size: 12px;\n"
"         color: #000000;\n"
"         min-width: 80px;\n"
"     }\n"
"     QPushButton:hover {\n"
"         background-color: #f0f0f0;\n"
"         border: 1px solid #0078d7;\n"
"     }\n"
"     QPushButton:pressed {\n"
"         background-color: #cce4f7;\n"
"         border: 1px solid #005499;\n"
"     }\n"
"    ")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 15, 20, 15)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_subtitle = QtWidgets.QLabel(self.centralwidget)
        self.label_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_subtitle.setObjectName("label_subtitle")
        self.verticalLayout.addWidget(self.label_subtitle)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_plain = QtWidgets.QLabel(self.centralwidget)
        self.label_plain.setObjectName("label_plain")
        self.gridLayout.addWidget(self.label_plain, 0, 0, 1, 1)
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.gridLayout.addWidget(self.txt_plain_text, 0, 1, 1, 1)
        self.label_key = QtWidgets.QLabel(self.centralwidget)
        self.label_key.setObjectName("label_key")
        self.gridLayout.addWidget(self.label_key, 1, 0, 1, 1)
        self.txt_key = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_key.setObjectName("txt_key")
        self.gridLayout.addWidget(self.txt_key, 1, 1, 1, 1)
        self.label_cipher = QtWidgets.QLabel(self.centralwidget)
        self.label_cipher.setObjectName("label_cipher")
        self.gridLayout.addWidget(self.label_cipher, 2, 0, 1, 1)
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.gridLayout.addWidget(self.txt_cipher_text, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.horizontalLayout.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.horizontalLayout.addWidget(self.btn_decrypt)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Playfair Cipher"))
        self.label_title.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.label_subtitle.setText(_translate("MainWindow", "Ngô Mạnh Hùng-2380600773"))
        self.label_plain.setText(_translate("MainWindow", "Plain Text:"))
        self.label_key.setText(_translate("MainWindow", "Key:"))
        self.label_cipher.setText(_translate("MainWindow", "CipherText:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
